version: '3'

services:
  webserver:
    image: php:7.4-apache
    container_name: lamp-webserver
    command: /bin/bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"
    ports:
      - "80:80" # maps pc port to container port
      - "443:443"
    volumes:
      - "./html/:/var/www/html"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: lamp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  db_data:
